import React from "react";

interface PreviewImageProps {
  src: string;
}

const PreviewImage: React.FC<PreviewImageProps> = ({ src }) => {
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState(false);

  React.useEffect(() => {
    setError(false);

    if (!src) {
      return;
    }
    setLoading(true);
  }, [src]);

  const renderImageAndLoading = () => {
    return (
      <>
        <img
          src={src}
          alt="Open Graph Image Generated by DOGimg"
          className="object-cover h-auto w-full inset-0"
          style={{ display: !loading ? "block" : "none" }}
          onLoad={() => setLoading(false)}
          onError={(e) => {
            setLoading(false);
            setError(true);
          }}
        />
        {loading && (
          <div className="inset-0 flex items-center justify-center">
            <div className="spinner border-t-2 border-gray-500"></div>
          </div>
        )}
      </>
    );
  };

  const renderNoImage = () => {
    return (
      <div className="inset-0 flex items-center justify-center">
        <div className="text-gray-500">No Image</div>
      </div>
    );
  };

  const renderError = () => {
    return (
      <div className="inset-0 flex items-center justify-center">
        <div className="text-red-500">Error Loading Image</div>
      </div>
    );
  };

  return (
    <div className="w-full">
      {error ? renderError() : src ? renderImageAndLoading() : renderNoImage()}
    </div>
  );
};

export default PreviewImage;
