import React from "react";
import Image from "next/image";

interface PreviewImageProps {
  src: string;
}

const PreviewImage: React.FC<PreviewImageProps> = ({ src }) => {
  const [displaySrc, setDisplaySrc] = React.useState("");
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState(false);

  React.useEffect(() => {
    setError(false);

    if (!src) {
      setDisplaySrc("");
      setLoading(false);
      return;
    }
    if (src === displaySrc) {
      setLoading(false);
      return;
    }

    setLoading(true);
    let cancelled = false;
    const preloader = new window.Image();
    preloader.onload = () => {
      if (cancelled) {
        return;
      }
      setDisplaySrc(src);
      setLoading(false);
    };
    preloader.onerror = () => {
      if (cancelled) {
        return;
      }
      setLoading(false);
      setError(true);
    };
    preloader.src = src;

    return () => {
      cancelled = true;
    };
  }, [src, displaySrc]);

  const renderMessage = (message: string, textClassName: string) => {
    return (
      <div className="absolute inset-0 flex items-center justify-center p-6 text-center">
        <div className={`text-lg sm:text-xl ${textClassName}`}>{message}</div>
      </div>
    );
  };

  return (
    <div className="w-full p-4 pt-2">
      <div className="relative w-full overflow-hidden rounded border border-gray-100 bg-gray-50 aspect-[1200/630]">
        {!src
          ? renderMessage(
              "Enter a URL to generate an open graph image",
              "text-gray-500"
            )
          : null}

        {displaySrc ? (
          <>
            <Image
              src={displaySrc}
              alt="Open Graph Image Generated by DOGimg"
              fill
              unoptimized
              sizes="(max-width: 1200px) 100vw, 1200px"
              className="object-cover"
            />
          </>
        ) : null}

        {loading ? (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="spinner border-t-2 border-gray-500"></div>
          </div>
        ) : null}
        {error && !displaySrc
          ? renderMessage("Error loading image", "text-red-600")
          : null}
      </div>
    </div>
  );
};

export default PreviewImage;
